<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fbd1704f-7c5e-42c3-a9b1-033deafcada9</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_29</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[3]/nav[1]/div[1]/ul[1]/a[11]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'View summary of organization activities.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>View summary of organization activities.</value>
        <webElementGuid>ecbd8a5e-a6c3-4d0a-bf72-9822f7504579</webElementGuid>
    </webElementProperties>
</WebElementEntity>