<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f2d89342-a668-4699-b6e0-7c1b6bd1f42a</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_7</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Recent Work')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Recent Work</value>
        <webElementGuid>a75af2a9-49bd-441d-b5c5-d5178ad6da24</webElementGuid>
    </webElementProperties>
</WebElementEntity>