<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1fa0834d-2ad2-4dd4-9a8b-e55bafc0be2a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_33</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[9]/div[3]/nav[1]/div[1]/ul[1]/a[9]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Manage your project settings.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Manage your project settings.</value>
        <webElementGuid>6df25c0e-4e66-4c65-98af-dadc9a9365df</webElementGuid>
    </webElementProperties>
</WebElementEntity>