<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1855fc88-80cb-4876-99ec-80b4be67a5a9</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_41</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/nav[1]/div[1]/ul[1]/a[8]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Update project information and other security configurations.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Update project information and other security configurations.</value>
        <webElementGuid>592a75d5-de4d-4e91-bca0-71c9fb9247b4</webElementGuid>
    </webElementProperties>
</WebElementEntity>