<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>608159eb-2a8c-4611-a696-5012cc0e32d6</elementGuidId>
    <imagePath></imagePath>
    <name>img_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[9]/div[2]/div[3]/div[1]/div[1]/main[1]/div[1]/div[1]/div[2]/div[1]/img[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>