<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>06b026bf-458c-4be5-90c8-b59a4eae70ac</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_19</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/nav[1]/div[1]/ul[1]/a[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Community Portal')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Community Portal</value>
        <webElementGuid>4ab07179-f134-44f5-9e0e-6157667575bf</webElementGuid>
    </webElementProperties>
</WebElementEntity>