<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>36526d30-1493-4ffd-8372-545e315d2700</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_23</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/nav[1]/div[1]/ul[1]/a[7]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Sign Out')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Sign Out</value>
        <webElementGuid>49caccf2-c579-4ac0-a029-d921966fe475</webElementGuid>
    </webElementProperties>
</WebElementEntity>