<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f8c5c62e-da9b-4d7d-9902-b6da50db4a7b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_16</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/nav[1]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Katalon Studio')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Katalon Studio</value>
        <webElementGuid>ec019b55-0c86-4be2-b36b-bdb37beacdc0</webElementGuid>
    </webElementProperties>
</WebElementEntity>