<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c03ed5ec-2839-4557-ad7c-96704fbcd26e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_24</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[4]/div[2]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Suites/TestOps/CE Automation - All Cases')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Suites/TestOps/CE Automation - All Cases</value>
        <webElementGuid>d91cb224-c6db-47f9-8e3b-7bf45d77b563</webElementGuid>
    </webElementProperties>
</WebElementEntity>