<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d95b225f-fa92-4497-a3fa-d922e9d95036</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_56</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[4]/div[2]/div[1]/div[1]/table[1]/tbody[1]/tr[14]/td[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Suites/_UI Regression Test Suites/Core Select/Daily Report - Core Select')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Suites/_UI Regression Test Suites/Core Select/Daily Report - Core Select</value>
        <webElementGuid>b877b988-643f-404e-b258-ad402209c4f3</webElementGuid>
    </webElementProperties>
</WebElementEntity>