<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ef55ac1f-2f34-4d42-a3b7-a284fea3ea7f</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_6</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>