<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>09f259c7-7e92-4a84-8175-0d1b23a59880</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_25</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[11]/td[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'20230605_031437\_UI Regression Test Suites\Core Select\Daily Report - Core Select\20230605_031634/1685949987302.png')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>20230605_031437\_UI Regression Test Suites\Core Select\Daily Report - Core Select\20230605_031634/1685949987302.png</value>
        <webElementGuid>f21b29fa-fb14-43a7-9bd3-5bd4148e4228</webElementGuid>
    </webElementProperties>
</WebElementEntity>