<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>90c761ff-4d71-4971-b376-2f5d283ab72b</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_56</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Case: XTA-229 As XCEED user, verify')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Case: XTA-229 As XCEED user, verify</value>
        <webElementGuid>8cbdac52-3a39-4798-b0bc-7bcd54ff87b0</webElementGuid>
    </webElementProperties>
</WebElementEntity>