<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a1406048-509c-4a8b-8584-547237e5935a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_45</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Cases/FAM-Jira Cards/FAM-729 (Stop Gate - Naming Lengths)/FAM-729 (Stop Gate - Naming Lengths - Over 50)')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Cases/FAM-Jira Cards/FAM-729 (Stop Gate - Naming Lengths)/FAM-729 (Stop Gate - Naming Lengths - Over 50)</value>
        <webElementGuid>d9d9f46c-16b1-48a5-a13b-d32777694e91</webElementGuid>
    </webElementProperties>
</WebElementEntity>