<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0965b5e4-fc4f-4dfe-b0bd-249ea0ed6c64</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_10</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[10]/div[3]/nav[1]/div[1]/ul[1]/a[7]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Manage your project settings.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Manage your project settings.</value>
        <webElementGuid>6c149555-a1ed-4066-94f1-aa372092e200</webElementGuid>
    </webElementProperties>
</WebElementEntity>