<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>505db104-f28b-4b9b-8731-d52df82ce722</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[5]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Suresh Kamaraju')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Suresh Kamaraju</value>
        <webElementGuid>e3ba2efc-beb3-4719-9eaa-c8364b8c56cc</webElementGuid>
    </webElementProperties>
</WebElementEntity>