<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3b8f5c17-c0b0-4b94-8028-2bf22de3ba11</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_8</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[5]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Judith Sewuster')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Judith Sewuster</value>
        <webElementGuid>0eee1e10-6142-4f44-915c-54ac618e1266</webElementGuid>
    </webElementProperties>
</WebElementEntity>