<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4c2c5c16-f66a-43ce-8699-461bb1b5b57f</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_68</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>