<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>583d0e93-f97d-40a8-953a-acafe59ce1e0</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_43</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/nav[1]/ul[1]/li[6]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Visual Testing')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Visual Testing</value>
        <webElementGuid>b7ae3db3-2e26-4f0f-a7d1-44898f6a22aa</webElementGuid>
    </webElementProperties>
</WebElementEntity>